services:
  pg:
    image: bitnami/postgresql:latest
    container_name: pg_brevly
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
    - POSTGRES_USER=docker
    - POSTGRES_PASSWORD=docker
    - POSTGRES_DB=brevly
    volumes:
      - './docker:/docker-entrypoint-initdb.d'
    networks:
      - brevly
      - db

  app:
    build: .
    depends_on:
      - pg
    container_name: brevly-server
    restart: unless-stopped
    ports:
      - 3333:3333
    environment:
      - PORT=3333
      - NODE_ENV=development
      - DATABASE_URL=postgresql://docker:docker@pg:5432/brevly
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=brevly
      - CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID
      - CLOUDFLARE_ACCESS_KEY_ID=$CLOUDFLARE_ACCESS_KEY_ID
      - CLOUDFLARE_SECRET_ACCESS_KEY=$CLOUDFLARE_SECRET_ACCESS_KEY
      - CLOUDFLARE_BUCKET=$CLOUDFLARE_BUCKET
      - CLOUDFLARE_PUBLIC_URL=$CLOUDFLARE_PUBLIC_URL
    networks:
      - brevly

volumes:
  db:
networks:
    brevly:
      driver: bridge
    db:
      driver: bridge